// #include <stdlib.h> 
// #include <stdio.h>
// #include <string.h>
extern void my_printf(const char* string, ...);

int main() {
    int h = 987;
    char* s = "123456789q24w";
    char* string = "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS100000000000000000000000000002000";
    my_printf("%s %x",s, h);
    return 0;
}
